### ISSUE TITLE
Temperature and humidity

### ISSUE THREAD

**Issue by kolbii** [RealZimboGuy/ewelink-api-java#1]
I just noticed temperature and humidity values are missing from Params class so I'm not able to get none of them.
Could you please add the following properties? Thanks

Example data:
`    params: {
      subDevId: '......',
      parentid: '......',
      battery: 100,
      trigTime: '1610748707290',
      temperature: '-82',
      humidity: '7465'
    },`

**Comment by RealZimboGuy** [comment]
Hi @kolbii 

i have added those fields just as strings for now to the param object, 

    <dependency>
      <groupId>com.github.realzimboguy.ewelink.api</groupId>
      <artifactId>ewelink-api-java</artifactId>
      <version>2.1.1-RELEASE</version>
    </dependency>

**Comment by leosurban** [comment]
Hi, this ("added to param object") is still true for last version? 

My result of gson.toJson(thing) is:

`{"itemType":1,"itemData":{"name":"Temperature 1","deviceid":"x","apikey":"x","extra":{"uiid":1770,"description":"ZCL_HA_DEVICEID_TEMPERATURE_SENSOR","brandId":"59e0dbc25c1af3a660cc1ac0","apmac":"00:00:00:00:00:00","mac":"x","ui":"ZigbeeSomeChineseCharsRemoved","modelInfo":"5be28aaf1a9a77c347a6047b","model":"NON-OTA-GL","manufacturer":"SomeChineseCharsRemoved"},"brandName":"coolkit","brandLogo":"","showBrand":false,"productModel":"ZCL_HA_DEVICEID_TEMPERATURE_SENSOR","tags":{},"devConfig":{},"family":{"familyid":"x","index":-1},"shareTo":[],"devicekey":"x","online":true,"params":{"bindInfos":{},"switch":"off","timeZone":1},"isSupportGroup":false,"isSupportedOnMP":true,"isSupportChannelSplit":false,"deviceFeature":{}},"index":-1}
`
Thank you very much.

**Comment by RealZimboGuy** [comment]
Hi @leosurban  i added them under that version, what fields are you missing ? 

![image](https://github.com/user-attachments/assets/54c9fb64-7757-4a24-9a8c-69463ba25f3e)

**Comment by RealZimboGuy** [comment]
ah i see, will try add them in

**Comment by leosurban** [comment]
Thank you very much.

**Comment by RealZimboGuy** [comment]
@leosurban  i have pushed the below new version with those fields added back in, probably a few hours for the maven cache to update or you can pull directly from the repo. let me know if it works
        
        <dependency>
          <groupId>com.github.realzimboguy.ewelink.api</groupId>
          <artifactId>ewelink-api-java</artifactId>
          <version>3.3.3-RELEASE</version>
        </dependency>

**Comment by leosurban** [comment]
Excellent, it is working, thank you very much.
Leos
