### ISSUE TITLE
{"error":400,"msg":"ValidationError: \"value\" must be of type object","data":{}}

### ISSUE THREAD

**Issue by AlexOdsUa** [RealZimboGuy/ewelink-api-java#10]
Hi
Today I received this answer from eWeLink. Is this a problem for everyone or just for me?
Thanks
![изображение](https://github.com/user-attachments/assets/333eaa76-e8db-4a83-bd25-dec60f10e5ff)

**Comment by RealZimboGuy** [comment]
just run the test class and still working fine for my user details

![image](https://github.com/user-attachments/assets/3de0f0b4-f70c-45e8-88c0-5943591af96e)

**Comment by RealZimboGuy** [comment]
ah, yes the getHomePage is doing as yours is 

![image](https://github.com/user-attachments/assets/7e592508-7f40-4a72-a3fe-a5e3e8e69fd5)

**Comment by RealZimboGuy** [comment]
@AlexOdsUa  ive pushed a new version with getFamily() that should solve a similar use and removed the getHomepage its not working anymore.  its not yet on maven central, as im having issues with the deploy at the moment but you can pull and build locally until then

**Comment by AlexOdsUa** [comment]
This is wonderful, thank you so much for your work and effort.

**Comment by RealZimboGuy** [comment]
3.3.0-RELEASE pushed to maven central
