### ISSUE TITLE
Increase Device Limit from 30 to 300 in getThings

### ISSUE THREAD

**Issue by tatianaovd** [RealZimboGuy/ewelink-api-java#11]
Hello,
I'm using your library and currently have 51 devices in eWeLink, and I expect that number to increase. Would it be possible to extend the device limit to 300? It would be greatly appreciated. Thank you!

![device_numbers](https://github.com/user-attachments/assets/ad0907a0-6038-465b-8c33-ef59acc3cea8)

**Comment by RealZimboGuy** [comment]
hi @tatianaovd , ive made the change and done a release, 3.3.1, (maven should update their caches in a few hours) let me know if its working as expected

**Comment by tatianaovd** [comment]
Yes, I checked, and it works correctly now. Thank you very much!
