### ISSUE TITLE
setDeviceStatus for things with multiple switches

### ISSUE THREAD

**Issue by jbaruch** [RealZimboGuy/ewelink-api-java#12]
It looks like `setDeviceStatus` assumes the thing has a single switch, as it sends the parameters as `"params":{"switch":"off"}`.
In case of Sonoff Micro-CFH the `itemData` shows the device to have four switches (outlets 0..3), controlled separately:
```    "params": {
      "switches": [
        {
          "outlet": 0,
          "switch": "on"
        },
        {
          "outlet": 1,
          "switch": "off"
        },
        {
          "outlet": 2,
          "switch": "off"
        },
        {
          "outlet": 3,
          "switch": "off"
        }
      ]
    }```

Because of that, `switch.itemData.params.switch` is `null`, and trying to set it to off fails. 

Looks like another variant of setDeviceStatus is needed, which will receive not only the status, but also the outlet ID of the switch needed to be controlled.

**Comment by RealZimboGuy** [comment]
Hi @jbaruch you can do a PR with the changes if needed and am happy to review and merge

**Comment by jbaruch** [comment]
I will be happy to, but I need some help. I couldn't find the official expected JSON schema for setting status anywhere. Can you point me in the right direction (documentation, examples)?

**Comment by RealZimboGuy** [comment]
so most of the code you see started from https://github.com/skydiver/ewelink-api , then a year or two ago most of which stopped working due to ewelink changing apis and moving things around. i thin reversed the mobile app and sniffed the traffic to find how the different commands are sent and received over the websocket.  have a look at the 

    public boolean setDeviceStatus(String deviceId, String status) throws Exception{

then the 

        Params params = new Params();
        params.setSwitch(status);
        statusChange.setParams(params);

the Params object  has the below field, try messing around with it and values and see if you can control your hardware

    @SerializedName("switches")
    @Expose
    private List<OutletSwitch> switches;
    
i dont have one with multiple outlets so testing is a shot in the dark. let me know if you get stuck

**Comment by jbaruch** [comment]
I got it. It looks like the best way to see what JSON needs to be sent to set status for multiple outlets is sniffing the outgoing traffic of the mobile app or a library that supports it. That complicates things a bit, but I'll try.

**Comment by jbaruch** [comment]
Aha, it might be the "channel" param: https://github.com/skydiver/ewelink-api/blob/master/docs/available-methods/setwsdevicepowerstate.md

**Comment by RealZimboGuy** [comment]
> I got it. It looks like the best way to see what JSON needs to be sent to set status for multiple outlets is sniffing the outgoing traffic of the mobile app or a library that supports it. That complicates things a bit, but I'll try.

ill try find it, so its a bit of a mission. their app uses certificate pinning so you have to decompile, remove it. recompile then you can man in the middle the ssl traffic

**Comment by RealZimboGuy** [comment]
@jbaruch you can DM me, i still have the apk installed and can intercept traffic, if you are up for it. you can send me the qr of a device and i can add it to my account and see what the traffic looks like

**Comment by jbaruch** [comment]
Let me see if I can make it work with the npm library. If it does work, the we don't need to sniff the traffic.

**Comment by RealZimboGuy** [comment]
> Let me see if I can make it work with the npm library. If it does work, the we don't need to sniff the traffic.

that one stopped working due to the ewelink api changes but worth a try as some things that were turned off i noticed they turned on again

**Comment by jbaruch** [comment]
You did right closing it because this functionality actually exists! `setMultiDeviceStatus` does exactly what I needed.
