### ISSUE TITLE
What Version of the Skydiver API is implemented here? Support for zeroconf?

### ISSUE THREAD

**Issue by whitedavidp** [RealZimboGuy/ewelink-api-java#2]
Skydiver's version 3.1.1 seems to be from 8/2020. This seems to be from 6/2021. But it is noted that not all has been implemented here. LAN-only mode (zeroconf) is essential to me. So wondering about it.

Thanks for all!

**Comment by RealZimboGuy** [comment]
hey @whitedavidp remind me what lan only is ? and any points in the code of reference from the skydiver version

**Comment by RealZimboGuy** [comment]
i see comments online of "LAN Mode enables Sonoff devices to be controlled directly on the local network using a WebSocket connection on port 8081." is that port open ? and not sure on what to send over the WS

**Comment by RealZimboGuy** [comment]
https://sonoff.tech/diy-developer/

looks like there are some more options on the table since i wrote this lib

**Comment by whitedavidp** [comment]
Hi and thanks for the reply. They refer to it as zeroconf or LAN-only mode. It is not quite the DIY mode of some Sonoff devices. But in the ewelink app and the Skydiver api (which I have not been able to get working on Android), this mode is supposed to supersede WAN mode if on LAN w/out internet.

The main marker for it appears to be URLs like http://192.168.1.xx:8080/zeroconf/... I have not found zeroconf in the code here.

My device doesn't seem to support DIY mode. But it IS supposed to support the LAN-only mode in that I can use/see it work via the ewelink app and by sniffing packets. I can see that json is sent/received. But at least part of the data being transferred seems to be encrypted somehow.

**Comment by RealZimboGuy** [comment]
lets use this to bounce ideas around if you want https://discord.gg/CjxSuGk3Pm

**Comment by whitedavidp** [comment]
Thanks. I tried going there (no account, never visited before) and it seems to have had some sort of problem.
