### ISSUE TITLE
lib is not able to authorize when setDeviceStatus(String deviceId, String status) status is called 

### ISSUE THREAD

**Issue by oncioiu** [RealZimboGuy/ewelink-api-java#3]
lib is successfully login, but when setDeviceStatus method is called, bellow error message is throw

responseLine = {"error":401,"errmsg":"no authorization"}

![image](https://user-images.githubusercontent.com/8328733/227981956-2e834ac7-df9a-404e-931b-844640ff7ca1.png)

**Comment by RealZimboGuy** [comment]
@oncioiu  is this with running the TestCode class file in the test package with your credentials? 

![image](https://user-images.githubusercontent.com/15829080/227984827-ab91dac3-da4d-4864-972f-dd249ad9e4d8.png)

**Comment by oncioiu** [comment]
No, I just use the lib as a gradle dependency. Please tell me if you need more info.
![image](https://user-images.githubusercontent.com/8328733/228001205-3d33ad35-1e4f-441c-9887-fc7a575ab37e.png)

**Comment by oncioiu** [comment]
Tried in this morning and everything was fine. Seems that "cloud" had problems. I will close the issue.
