### ISSUE TITLE
unable to control multi channel device

### ISSUE THREAD

**Issue by dvorap** [RealZimboGuy/ewelink-api-java#6]
Hi, nice work! 

but it is unable to control multi-channel devices, for example, TX2C. 

Are you planning to support it?

Thank you

**Comment by RealZimboGuy** [comment]
Hi, I've never had one of those devices to "play" with do you have any info
about how it responds or behavior with the current code? We can made
modifications as needed.

**Comment by dvorap** [comment]
I guess you have to put an object "switches" into the "params" field. This is an example of message from WebSocket update action:
`{
  "action": "Update",
  "deviceid": "multi-channel-device",
  "apikey": "--",
  "userAgent": "device",
  "params": {
    "switches": [
      {
        "switch": "off",
        "outlet": 0
      },
      {
        "switch": "on",
        "outlet": 1
      },
      {
        "switch": "off",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ]
  },
  "seq": "55"
}`

and this is an example of single channel device:
`{
  "action": "update",
  "deviceid": "single-cahnnel-device",
  "apikey": "--",
  "userAgent": "device",
  "params": {
    "switch": "on"
  },
  "seq": "72"
}`

Yeah, I know terrible design form ewelink  🤷

**Comment by RealZimboGuy** [comment]
OK, it looks doable based on that, does the message from ewelink on the
websocket look similar when you change a switch state via other platform
/manually? I might only have time in a few days to check the code but you
are welcome to do a pull req for the changes

**Comment by RealZimboGuy** [comment]
have a look at 3.1.0-RELEASE, a few changes, you should be able to access the switch values thing.getItemData().getParams().getSwitches() and then based on that i added the eweLink.setMultiDeviceStatus(<id>,<list of status>)

you will i think need to push all the outlet status changes at the same time im not sure you can just send ie outlet 3 off, but im not sure you will have to test and let me know

**Comment by dvorap** [comment]
I tested it, and it works. You can even send just one outlet, don't need to send it all.
That is exactly what I need, thank you, I really appreciate it 👍
