### ISSUE TITLE
Is it possible to switch family?

### ISSUE THREAD

**Issue by kun3ar** [RealZimboGuy/ewelink-api-java#8]
Hi. Will it be possible to switch family? Currently when program log in, it fetches data for the current family only.

**Comment by RealZimboGuy** [comment]
it was my understanding when the hompage endpoint is called you get a list of Family and the list of things, hence why to return the things it uses "getHomePage().getData().getThingInfo().getThingList()"

if you enable debug logging you should see the object come back 09:54:40.445 [main] DEBUG com.github.realzimboguy.ewelink.api.EweLink - getHome Response Raw:

ive looked in my android app, how do you change family ?

**Comment by kun3ar** [comment]
HiI have multiple families and in my app I am able to switch families. Families are called Homes in my app. See attached I have debugged the data. The homepage returns 1. List of families 2. Current Selected Family (the selected family was what I selected in app)3. Things belonging to current selected family only there is no function to pass on the family id parameter or switch family. KunwarSent from my iPhoneOn 5 Feb 2024, at 07:58, RealZimboGuy ***@***.***> wrote:﻿
it was my understanding when the hompage endpoint is called you get a list of Family and the list of things, hence why to return the things it uses "getHomePage().getData().getThingInfo().getThingList()"
if you enable debug logging you should see the object come back 09:54:40.445 [main] DEBUG com.github.realzimboguy.ewelink.api.EweLink - getHome Response Raw:
ive looked in my android app, how do you change family ?

**Comment by RealZimboGuy** [comment]
github seems to strip attachments in email replies

**Comment by kun3ar** [comment]
Sent from my iPhoneOn 5 Feb 2024, at 12:01, RealZimboGuy ***@***.***> wrote:﻿
github seems to strip attachments in email replies

**Comment by kun3ar** [comment]
![0147B61D-A30E-4D13-9379-2A2754AA101D](https://github.com/RealZimboGuy/ewelink-api-java/assets/158823916/a564f0a9-29ec-430f-a434-89ad1c27a603)
![01359341-2AE2-4827-9CB3-A3F3871B0386](https://github.com/RealZimboGuy/ewelink-api-java/assets/158823916/0d48d3d4-ed03-41a1-99ab-7e163716b6b2)

**Comment by RealZimboGuy** [comment]
Ive found an endpoint that should solve your issue, the code is comitted "3.2.0-RELEASE" but there seems issues publishing to maven at the moment, you will need to pull/download the code and run a local maven install. let me know if it works 

    public List<Thing> getThings(String familyId) throws Exception

**Comment by kun3ar** [comment]
Hi. It worked fine.

Thank you for the fix.

Best of luck

**Comment by RealZimboGuy** [comment]
great
